### ISSUE TITLE
0 MO values

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#142]
## Detailed Description
Found that all MO variables are 0 in batch

## Context
- by using #114 , found error

## Possible Implementation
- look why they are zero?
- check are they zero in original data

**Comment by peterdudfield** [comment]
looks like the values in raw zarr are non-zero

![Screenshot 2024-11-26 at 17 03 00](https://github.com/user-attachments/assets/eea64468-4259-4d99-8707-6a866284c43c)

**Comment by peterdudfield** [comment]
I see this logging statement `INFO:ocf_datapipes.training.common:Filled NaNs with zeros - {'BatchKey.nwp/mo_global/NWPBatchKey.nwp', 'BatchKey.nwp/ecmwf/NWPBatchKey.nwp'}
`

**Comment by peterdudfield** [comment]
These values are in the raw dataset
![Screenshot 2024-11-26 at 17 56 25](https://github.com/user-attachments/assets/313f356f-2fcd-48bb-bf8e-958b098b44b6)

**Comment by peterdudfield** [comment]
Spatial resolution may be different in archive and live

**Comment by Sukh-P** [comment]
So just double checked and in training the batches looked fine and the MO global data were non zeros, also double checked and there is a difference between archive and live for MO global data which means that coarsening would not be applied in training but would in live and this can cause issues as there would be some padding with 0s so the shapes match (recorded in a separate issue now since a similar thing occurs with ECMWF)

**Comment by peterdudfield** [comment]
Solved in 1.1.16

**Comment by peterdudfield** [comment]
No longer zero, 

Note that v1, v2 and v3 of windnet_mo global, have the same data in the npw mo_global part for the batch. This seems a bit odd given the difference in configruation

**Comment by peterdudfield** [comment]
Weird that the batch size is 50 by 50

**Comment by peterdudfield** [comment]
Ok, the ECMWF is different. V1 is 21 pixels, and v2 and v3 is 42 pixels. Also note that 21 is flipped comapred to v2 and v3

**Comment by Sukh-P** [comment]
> 
Weird that the batch size is 50 by 50

If this is about MO that is because there is no `coarsen_to_degrees` parameter in the data_config for MO currently, this should be fixed by the regridding work so the same spatial area is covered in training and live
