### ISSUE TITLE
Add Pvnet 2 hours smoothing

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#60]
## Detailed Description
Add Pvnet 2 hours smoothing

## Context
- similar to wind smoothing

## Possible Implementation
similar - https://github.com/openclimatefix/india-forecast-app/blob/main/india_forecast_app/models/pvnet/model.py#L126

**Comment by peterdudfield** [comment]
@jacobbieker what do you think? Might be good for @dfulu to try this

**Comment by jacobbieker** [comment]
Yeah, we can, I have the same reservations about using it like with the wind one, but if we want it to look better, then sure

**Comment by peterdudfield** [comment]
> Yeah, we can, I have the same reservations about using it like with the wind one, but if we want it to look better, then sure

I understand, but do you agree it improves the 0-2 hour forecast? 
How we display the forecast is perhaps more of a UI, UX question

**Comment by peterdudfield** [comment]
Can @jacobbieker decide if you or @dfulu do this?
Thanks
