### ISSUE TITLE
Increase solar forecast

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#61]
## Detailed Description
Shoiuld we increase the solar capacity? 
I think we trained as this was the maximum generation. Now the maximum generation seems higher

## Context

<img width="735" alt="Screenshot 2024-04-08 at 13 15 30" src="https://github.com/openclimatefix/india-forecast-app/assets/34686298/95624f2b-9357-49a7-ac4b-0b2574b2e6ee">

## Possible Implementation
Update value in database

**Comment by peterdudfield** [comment]
@jacobbieker @dfulu what do you think?

**Comment by jacobbieker** [comment]
Yeah, the max never got to around 4000 like it is here, so upping it seems fine

**Comment by jacobbieker** [comment]
Maybe like 200 MW? Current max I think is 3773, and this seems to go about 200MW higher

**Comment by peterdudfield** [comment]
@jacobbieker you ok to follow up with @devsjc to do this?

**Comment by jacobbieker** [comment]
Yep

**Comment by jacobbieker** [comment]
Its now been updated to 3973 MW from 3773.
