### ISSUE TITLE
Adjust solar capacity

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#69]
Currently looks like we are under a bit on PV. 
- analysis of last few days to see if we are regular under
- analysis of 5 years of data, to understand capacity of the entire system

**Comment by kimaya000** [comment]
hey i am trying to run the application on docker but i am getting this error when i paste the below line. how to fix it? sorry, i'm a beginner.
DB_URL=postgresql://postgres:postgres@localhost:54545/postgres poetry run seeder

Command not found: seeder

**Comment by peterdudfield** [comment]
@ADIMANV has made a report of this. Ill close this for the moment
