### ISSUE TITLE
Remove smoothing on soalr

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#71]
Last few days we have not had smoothing on solar, due to role back issues. The forecast looks a lot better. 

This may effect #69 

So we would have to role back #62 but keep it on wind

<img width="494" alt="Screenshot 2024-05-07 at 06 15 20" src="https://github.com/openclimatefix/india-forecast-app/assets/34686298/785860d8-b655-49d2-8a0b-8f3970d68c12">

**Comment by peterdudfield** [comment]
Yea sure

**Comment by vishalj0501** [comment]
Hi, 
Can I please have more information on this? I am having some trouble replicating this repo locally.

**Comment by peterdudfield** [comment]
Its basically to role back #62, so smoothing only happens on the wind forecast

**Comment by vishalj0501** [comment]
So, should the fix be like this: https://github.com/openclimatefix/india-forecast-app/blob/fdf296ae4fea9923e070c912e9125326eccc3f0b/india_forecast_app/models/pvnet/model.py#L126

And also I'm trying to run it locally, facing some issues with docker.build. So I can't the test the changes i've made..

**Comment by peterdudfield** [comment]
SOrry @vishalj0501, ive pushed this one forward as i needed it for production

**Comment by vishalj0501** [comment]
Sure!, Sorry for the late.
I'll look into more issues across OCF repos.
Thank You
