### ISSUE TITLE
Windnet GFS live

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#81]
Save model to hugging face
update model to run. 

We might need to blend to models together

**Comment by Sukh-P** [comment]
The model trained with GFS data can be found [here](https://huggingface.co/openclimatefix/windnet_india/tree/2371dc18685a8983167fafd3c81c55ed6e5f713f) 
This has now been deployed to our [dev environment](https://dev.quartz.energy/) where we will monitor it's performance compared to the current prod WindNet model

**Comment by Sukh-P** [comment]
The model has been deployed to Prod now due to it's improved performance for DA forecasting, so will close this issue for now, we will be deploying a newer version to dev/prod soon as well with added time features
